### ISSUE TITLE
Pipeline task logs only available for the first stage

### ISSUE THREAD

**Issue by rossbuggins** [PurpleSoftSrl/azure_devops_app#35]
On multistage yaml pipelines we can only see the tasks for the first (build) stage, they are not shown for the deploy stages

**Comment by tiz-sharp** [comment]
Hi @rossbuggins,  @bonddim

Thanks for reporting this issue! 🚀 To investigate further, we need a few more details:  

- Are you experiencing this behavior with **all multistage YAML pipelines**, or just specific ones?  
- Could you share a sample pipeline YAML definition (or a simplified version) where the issue occurs?  
Let us know, and we’ll be happy to look into it! 
Thanks for your support. 🔍🚀  

— **PurpleSoft Team**

**Comment by bonddim** [comment]
Hi @tiz-sharp ,
This behavior is experienced with **deployment** jobs only.

Examples:
<details>
<summary>two simple jobs (works as expected)</summary>

```yaml
pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build
    steps:
      - checkout: none
      - script: echo "Building..."
        displayName: "Building..."

  - job: DependentJob
    dependsOn: Build
    steps:
      - checkout: none
      - script: echo "Some Job..."
        displayName: "echo..."
```

![Image](https://github.com/user-attachments/assets/f4ca7884-660a-420a-9528-87b2cada6eca)

</details>
<details>
<summary>multi-stage</summary>

```yaml
pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    jobs:
      - job: Build
        steps:
          - checkout: none
          - script: echo "Building..."
            displayName: "Building..."

  - stage: CD
    jobs:
      - deployment: Deploy
        environment: sandbox
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying..."
                  displayName: "Deploying..."
```

![Image](https://github.com/user-attachments/assets/7d1b065b-8162-46a8-afcd-85e71f405ea2)

</details>

<details>
<summary>multi-job</summary>

```yaml
pool:
  vmImage: ubuntu-latest

jobs:
  - job: Build
    steps:
      - checkout: none
      - script: echo "Building..."
        displayName: "Building..."

  - deployment: Deploy
    environment: sandbox
    dependsOn: Build
    strategy:
      runOnce:
        deploy:
          steps:
            - script: echo "Deploying..."
              displayName: "Deploying..."
```

![Image](https://github.com/user-attachments/assets/efbbf370-1b34-4425-b3ad-40450033f76b)

</details>

<details>
<summary>multi-stage with simple job after deployment</summary>

```yaml
pool:
  vmImage: ubuntu-latest

stages:
  - stage: CI
    jobs:
      - job: Build
        steps:
          - script: echo "Building..."
            displayName: "Building..."

  - stage: CD
    jobs:
      - deployment: Deploy
        environment: sandbox
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying..."
                  displayName: "Deploying..."
      - job: PostDeploy
        dependsOn: Deploy
        steps:
          - checkout: none
          - script: echo "Post-deploying..."
            displayName: "Post-deploying..."
```

![Image](https://github.com/user-attachments/assets/3ef2abf2-ec62-448d-bdee-e3eef6b2f0bd)

</details>
